name: Bug Report
description: Something isn't working correctly
labels: ["bug"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application is affected?
      options:
        - Frontend
        - Backend
        - Both
    validations:
      required: true

  - type: dropdown
    id: entity
    attributes:
      label: Entity Type
      description: Which entity type is affected (if applicable)?
      options:
        - Spells
        - Monsters
        - Items
        - Races
        - Classes
        - Backgrounds
        - Feats
        - Character Wizard
        - Global Search
        - N/A
    validations:
      required: false

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Brief description of the bug
      placeholder: One or two sentences describing the problem
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Where
      description: Endpoint, component, page, or user flow affected
      placeholder: "e.g., GET /api/v1/spells, SpellCard component, /spells/fireball page"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What happens instead?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this?
      options:
        - "High - Blocking or breaking functionality"
        - "Medium - Important but has workaround"
        - "Low - Minor issue"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Error messages, screenshots, logs, or other relevant information
    validations:
      required: false
